import { NextRequest, NextResponse } from "next/server";
import { createHmac, timingSafeEqual } from "crypto";
import { prisma } from "@/lib/db";
import { getAuthUser, unauthorized } from "@/lib/auth";
import { normalizeAccessCode, parseAccessCodeQrPayload } from "@/lib/accessCode";
import { isRateLimited } from "@/lib/rateLimit";
import { NO_DAY, EVENT_TZ, resolveEventDay, resolveDoorsOpenAt } from "@/lib/eventDay";

if (!process.env.QR_SECRET) throw new Error("QR_SECRET env var not set — refusing to start");
const QR_SECRET: string = process.env.QR_SECRET;
const WINDOW_SECS = 30;

// Validates the rotating QR payload and returns tokenId + userId, or null if invalid.
// Format: tessera:v1:{tokenId}:{window}:{userId}:{sig}
function validateQrPayload(payload: string): { tokenId: number; userId: string } | null {
  const parts = payload.split(":");
  if (parts.length !== 6 || parts[0] !== "tessera" || parts[1] !== "v1") return null;

  const tokenId = parseInt(parts[2], 10);
  const window  = parseInt(parts[3], 10);
  const userId  = parts[4];
  const sig     = parts[5];

  if (isNaN(tokenId) || isNaN(window) || !userId) return null;

  const currentWindow = Math.floor(Date.now() / (WINDOW_SECS * 1000));
  // Accept current window and ±1 (30s tolerance for clock skew)
  if (Math.abs(currentWindow - window) > 1) return null;

  const expectedSig = createHmac("sha256", QR_SECRET)
    .update(`${tokenId}:${window}:${userId}`)
    .digest("hex");

  if (sig.length !== expectedSig.length) return null;
  if (!timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null;

  return { tokenId, userId };
}

// POST /api/checkin
// Body: { qrPayload: string } — ingresso (QR rotativo) OU código de entrada
// (QR com prefixo "tessera:code:v1:" ou os 10 caracteres digitados direto).
// Auth: any authenticated user with STAFF or ADMIN role
//
// PLANO_EVOLUCAO_V2.md §10.5/D41 — um endpoint só, não uma aba separada como
// o D20 previa: a tela de check-in tem uma câmera e um campo; obrigar o
// operador a escolher o modo antes de escanear é fricção na porta, onde tem
// fila. O servidor decide pela forma do que chegou.
export async function POST(req: NextRequest) {
  const user = await getAuthUser(req);
  if (!user) return unauthorized();

  if (user.role !== "STAFF" && user.role !== "ADMIN") {
    return NextResponse.json({ error: "Forbidden — STAFF or ADMIN role required" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { qrPayload, accessCode } = body as { qrPayload?: string; accessCode?: string };

  if (!qrPayload && !accessCode) {
    return NextResponse.json({ error: "qrPayload or accessCode is required" }, { status: 400 });
  }

  // Forma decide o fluxo: accessCode explícito, ou qrPayload com o prefixo
  // do código, cai no check-in por código; senão, é o QR de ingresso normal.
  const codeFromQr = qrPayload ? parseAccessCodeQrPayload(qrPayload.trim()) : null;
  const rawCode = accessCode ?? codeFromQr;

  if (rawCode !== null) {
    return handleAccessCodeCheckin(rawCode, user.id);
  }

  return handleTicketCheckin(qrPayload!.trim(), user.id);
}

async function handleTicketCheckin(qrPayload: string, staffUserId: string) {
  const parsed = validateQrPayload(qrPayload);
  if (parsed === null) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }
  const { tokenId, userId } = parsed;

  const ticket = await prisma.ticket.findUnique({
    where:   { tokenId },
    include: {
      event:      { select: { title: true, venue: true, city: true, eventDate: true, ticketDays: true, doorsOpenAt: true } },
      // dayIds: para QUAIS dias este ingresso vale (passe = mais de um).
      // earlyEntryMinutes: quantos minutos antes do portão ele pode entrar.
      ticketType: { select: { dayIds: true, label: true, earlyEntryMinutes: true } },
    },
  });

  if (!ticket) {
    return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
  }

  // Verify the QR was generated by the current ticket owner, not someone who previously held it
  const ticketOwner = await prisma.user.findFirst({
    where: { walletAddress: { equals: ticket.ownerAddress, mode: "insensitive" } },
  });
  if (!ticketOwner || ticketOwner.id !== userId) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }

  // CHECKED_IN não barra mais: com check-in por dia ele só significa "já
  // entrou em ALGUM dia" — quem decide se pode entrar HOJE é a unicidade
  // (tokenId, dayId) logo abaixo. LISTED/FROZEN seguem barrados.
  if (ticket.status !== "VALID" && ticket.status !== "CHECKED_IN") {
    return NextResponse.json({
      error: `Ticket cannot be checked in — current status: ${ticket.status}`,
      tokenId,
    }, { status: 409 });
  }

  // Qual dia do evento é hoje (lib/eventDay.ts). Evento sem dimensão de dia,
  // ou multi-dia legado sem datas gravadas, cai no sentinela NO_DAY — que
  // preserva exatamente o comportamento antigo de "um check-in por ingresso".
  const resolution = resolveEventDay(ticket.event.ticketDays);
  if (resolution.kind === "outside") {
    return NextResponse.json({
      error: `Hoje (${resolution.today}) não é um dia deste evento`,
      tokenId,
    }, { status: 409 });
  }
  const dayId = resolution.kind === "resolved" ? resolution.dayId : NO_DAY;

  // O ingresso vale pra um CONJUNTO de dias — um dia só no ingresso comum,
  // vários no passe. Basta hoje estar no conjunto; é isso que faz o mesmo
  // passe entrar no dia 1, no 2 e no 3 sem tratamento especial.
  const ticketDayIds = ticket.ticketType?.dayIds ?? [];
  if (resolution.kind === "resolved" && ticketDayIds.length > 0 && !ticketDayIds.includes(dayId)) {
    return NextResponse.json({
      error: `Este ingresso é de outro dia (${ticket.ticketType?.label})`,
      tokenId,
    }, { status: 409 });
  }

  // Portão. `earlyEntryMinutes` é o perk do passe ultra: entra N minutos
  // antes de todo mundo. Só existe gate quando o evento declara abertura de
  // portões — sem doorsOpenAt o comportamento é o de antes (entra a qualquer
  // hora do dia do evento), pra não passar a barrar eventos já publicados.
  const doorsAt = resolveDoorsOpenAt(ticket.event.doorsOpenAt, ticket.event.ticketDays, dayId);
  if (doorsAt) {
    const earlyMin = ticket.ticketType?.earlyEntryMinutes ?? 0;
    const allowedFrom = new Date(doorsAt.getTime() - earlyMin * 60_000);
    if (Date.now() < allowedFrom.getTime()) {
      return NextResponse.json({
        error: earlyMin > 0
          ? `Entrada antecipada deste ingresso começa às ${formatTime(allowedFrom)}`
          : `Os portões abrem às ${formatTime(allowedFrom)}`,
        tokenId,
      }, { status: 409 });
    }
  }

  try {
    await prisma.$transaction([
      prisma.ticket.update({
        where: { tokenId },
        data:  { status: "CHECKED_IN" },
      }),
      prisma.checkin.create({
        data: {
          tokenId,
          eventId:     ticket.eventId,
          dayId,
          staffUserId,
        },
      }),
    ]);
  } catch (err) {
    // A UNIQUE é o guard real contra reentrada — não um SELECT antes do
    // INSERT, que perde a corrida de dois leitores na mesma catraca.
    if (isUniqueViolation(err)) {
      return NextResponse.json({ error: "Ticket already checked in", tokenId }, { status: 409 });
    }
    throw err;
  }

  // ticketDays fora da resposta — é estrutura interna da matriz, a tela de
  // porta só precisa identificar o evento.
  const { ticketDays: _ticketDays, ...eventInfo } = ticket.event;

  return NextResponse.json({
    ok:           true,
    kind:         "ticket",
    tokenId,
    ticketNumber: ticket.ticketNumber,
    seat:         ticket.seat,
    event:        eventInfo,
    dayName:      resolution.kind === "resolved" ? dayNameOf(ticket.event.ticketDays, dayId) : null,
  });
}

// Hora no fuso do evento — a portaria lê "abre às 10:00", não um ISO em UTC.
function formatTime(d: Date): string {
  return new Intl.DateTimeFormat("pt-BR", {
    timeZone: EVENT_TZ, hour: "2-digit", minute: "2-digit", hour12: false,
  }).format(d);
}

function dayNameOf(ticketDays: unknown, dayId: string): string | null {
  const days = (ticketDays as { id: string; name: string }[] | null) ?? [];
  return days.find((d) => d.id === dayId)?.name ?? null;
}

function isUniqueViolation(err: unknown): boolean {
  return typeof err === "object" && err !== null && (err as { code?: string }).code === "P2002";
}

// PLANO_EVOLUCAO_V2.md §10.5-10.6/D41-D43 — entrada por código vira
// AccessEntry, NÃO Checkin: Checkin.tokenId exige Ticket, que entrada por
// código não tem. Fundir os dois faria computeAchievements contar presença
// de quem não tem colecionável como conquista.
async function handleAccessCodeCheckin(rawCode: string, staffUserId: string) {
  // Força bruta é o único ataque que a entropia do código não elimina
  // sozinha — por staffUserId porque a rota já exige STAFF/ADMIN autenticado.
  if (isRateLimited(`checkin:${staffUserId}`, 30, 60_000)) {
    return NextResponse.json({ error: "Too many attempts — wait a moment" }, { status: 429 });
  }

  const code = normalizeAccessCode(rawCode);

  try {
    const result = await prisma.$transaction(async (tx) => {
      const accessCode = await tx.accessCode.findUnique({
        where: { code },
        include: { event: { select: { title: true, venue: true, city: true, eventDate: true } } },
      });
      if (!accessCode) throw new CheckinError("Invalid access code", 422);
      if (accessCode.revokedAt !== null) throw new CheckinError("Access code was revoked", 409);
      if (accessCode.usedAt !== null) throw new CheckinError("Access code already used", 409);

      const now = new Date();
      await tx.accessCode.update({ where: { id: accessCode.id }, data: { usedAt: now } });
      await tx.accessEntry.create({
        data: { accessCodeId: accessCode.id, eventId: accessCode.eventId, staffUserId, scannedAt: now },
      });

      return { label: accessCode.label, event: accessCode.event };
    });

    return NextResponse.json({ ok: true, kind: "access_code", label: result.label, event: result.event });
  } catch (err) {
    if (err instanceof CheckinError) {
      return NextResponse.json({ error: err.message }, { status: err.status });
    }
    throw err;
  }
}

class CheckinError extends Error {
  constructor(message: string, public status: number) {
    super(message);
  }
}
