import { NextRequest, NextResponse } from "next/server";
import { createHmac, timingSafeEqual } from "crypto";
import { prisma } from "@/lib/db";
import { getAuthUser, unauthorized } from "@/lib/auth";
import { normalizeAccessCode, parseAccessCodeQrPayload } from "@/lib/accessCode";
import { isRateLimited } from "@/lib/rateLimit";

if (!process.env.QR_SECRET) throw new Error("QR_SECRET env var not set — refusing to start");
const QR_SECRET: string = process.env.QR_SECRET;
const WINDOW_SECS = 30;

// Validates the rotating QR payload and returns tokenId + userId, or null if invalid.
// Format: tessera:v1:{tokenId}:{window}:{userId}:{sig}
function validateQrPayload(payload: string): { tokenId: number; userId: string } | null {
  const parts = payload.split(":");
  if (parts.length !== 6 || parts[0] !== "tessera" || parts[1] !== "v1") return null;

  const tokenId = parseInt(parts[2], 10);
  const window  = parseInt(parts[3], 10);
  const userId  = parts[4];
  const sig     = parts[5];

  if (isNaN(tokenId) || isNaN(window) || !userId) return null;

  const currentWindow = Math.floor(Date.now() / (WINDOW_SECS * 1000));
  // Accept current window and ±1 (30s tolerance for clock skew)
  if (Math.abs(currentWindow - window) > 1) return null;

  const expectedSig = createHmac("sha256", QR_SECRET)
    .update(`${tokenId}:${window}:${userId}`)
    .digest("hex");

  if (sig.length !== expectedSig.length) return null;
  if (!timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null;

  return { tokenId, userId };
}

// POST /api/checkin
// Body: { qrPayload: string } — ingresso (QR rotativo) OU código de entrada
// (QR com prefixo "tessera:code:v1:" ou os 10 caracteres digitados direto).
// Auth: any authenticated user with STAFF or ADMIN role
//
// PLANO_EVOLUCAO_V2.md §10.5/D41 — um endpoint só, não uma aba separada como
// o D20 previa: a tela de check-in tem uma câmera e um campo; obrigar o
// operador a escolher o modo antes de escanear é fricção na porta, onde tem
// fila. O servidor decide pela forma do que chegou.
export async function POST(req: NextRequest) {
  const user = await getAuthUser(req);
  if (!user) return unauthorized();

  if (user.role !== "STAFF" && user.role !== "ADMIN") {
    return NextResponse.json({ error: "Forbidden — STAFF or ADMIN role required" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { qrPayload, accessCode } = body as { qrPayload?: string; accessCode?: string };

  if (!qrPayload && !accessCode) {
    return NextResponse.json({ error: "qrPayload or accessCode is required" }, { status: 400 });
  }

  // Forma decide o fluxo: accessCode explícito, ou qrPayload com o prefixo
  // do código, cai no check-in por código; senão, é o QR de ingresso normal.
  const codeFromQr = qrPayload ? parseAccessCodeQrPayload(qrPayload.trim()) : null;
  const rawCode = accessCode ?? codeFromQr;

  if (rawCode !== null) {
    return handleAccessCodeCheckin(rawCode, user.id);
  }

  return handleTicketCheckin(qrPayload!.trim(), user.id);
}

async function handleTicketCheckin(qrPayload: string, staffUserId: string) {
  const parsed = validateQrPayload(qrPayload);
  if (parsed === null) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }
  const { tokenId, userId } = parsed;

  const ticket = await prisma.ticket.findUnique({
    where:   { tokenId },
    include: { event: { select: { title: true, venue: true, city: true, eventDate: true } } },
  });

  if (!ticket) {
    return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
  }

  // Verify the QR was generated by the current ticket owner, not someone who previously held it
  const ticketOwner = await prisma.user.findFirst({
    where: { walletAddress: { equals: ticket.ownerAddress, mode: "insensitive" } },
  });
  if (!ticketOwner || ticketOwner.id !== userId) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }

  if (ticket.status === "CHECKED_IN") {
    return NextResponse.json({ error: "Ticket already checked in", tokenId }, { status: 409 });
  }
  if (ticket.status !== "VALID") {
    return NextResponse.json({
      error: `Ticket cannot be checked in — current status: ${ticket.status}`,
      tokenId,
    }, { status: 409 });
  }

  await prisma.$transaction([
    prisma.ticket.update({
      where: { tokenId },
      data:  { status: "CHECKED_IN" },
    }),
    prisma.checkin.create({
      data: {
        tokenId,
        eventId:     ticket.eventId,
        staffUserId,
      },
    }),
  ]);

  return NextResponse.json({
    ok:           true,
    kind:         "ticket",
    tokenId,
    ticketNumber: ticket.ticketNumber,
    seat:         ticket.seat,
    event:        ticket.event,
  });
}

// PLANO_EVOLUCAO_V2.md §10.5-10.6/D41-D43 — entrada por código vira
// AccessEntry, NÃO Checkin: Checkin.tokenId exige Ticket, que entrada por
// código não tem. Fundir os dois faria computeAchievements contar presença
// de quem não tem colecionável como conquista.
async function handleAccessCodeCheckin(rawCode: string, staffUserId: string) {
  // Força bruta é o único ataque que a entropia do código não elimina
  // sozinha — por staffUserId porque a rota já exige STAFF/ADMIN autenticado.
  if (isRateLimited(`checkin:${staffUserId}`, 30, 60_000)) {
    return NextResponse.json({ error: "Too many attempts — wait a moment" }, { status: 429 });
  }

  const code = normalizeAccessCode(rawCode);

  try {
    const result = await prisma.$transaction(async (tx) => {
      const accessCode = await tx.accessCode.findUnique({
        where: { code },
        include: { event: { select: { title: true, venue: true, city: true, eventDate: true } } },
      });
      if (!accessCode) throw new CheckinError("Invalid access code", 422);
      if (accessCode.revokedAt !== null) throw new CheckinError("Access code was revoked", 409);
      if (accessCode.usedAt !== null) throw new CheckinError("Access code already used", 409);

      const now = new Date();
      await tx.accessCode.update({ where: { id: accessCode.id }, data: { usedAt: now } });
      await tx.accessEntry.create({
        data: { accessCodeId: accessCode.id, eventId: accessCode.eventId, staffUserId, scannedAt: now },
      });

      return { label: accessCode.label, event: accessCode.event };
    });

    return NextResponse.json({ ok: true, kind: "access_code", label: result.label, event: result.event });
  } catch (err) {
    if (err instanceof CheckinError) {
      return NextResponse.json({ error: err.message }, { status: err.status });
    }
    throw err;
  }
}

class CheckinError extends Error {
  constructor(message: string, public status: number) {
    super(message);
  }
}
