import { NextRequest, NextResponse } from "next/server";
import { createHmac, timingSafeEqual } from "crypto";
import { prisma } from "@/lib/db";
import { getAuthUser, unauthorized } from "@/lib/auth";

if (!process.env.QR_SECRET) throw new Error("QR_SECRET env var not set — refusing to start");
const QR_SECRET: string = process.env.QR_SECRET;
const WINDOW_SECS = 30;

// Validates the rotating QR payload and returns tokenId + userId, or null if invalid.
// Format: tessera:v1:{tokenId}:{window}:{userId}:{sig}
function validateQrPayload(payload: string): { tokenId: number; userId: string } | null {
  const parts = payload.split(":");
  if (parts.length !== 6 || parts[0] !== "tessera" || parts[1] !== "v1") return null;

  const tokenId = parseInt(parts[2], 10);
  const window  = parseInt(parts[3], 10);
  const userId  = parts[4];
  const sig     = parts[5];

  if (isNaN(tokenId) || isNaN(window) || !userId) return null;

  const currentWindow = Math.floor(Date.now() / (WINDOW_SECS * 1000));
  // Accept current window and ±1 (30s tolerance for clock skew)
  if (Math.abs(currentWindow - window) > 1) return null;

  const expectedSig = createHmac("sha256", QR_SECRET)
    .update(`${tokenId}:${window}:${userId}`)
    .digest("hex");

  if (sig.length !== expectedSig.length) return null;
  if (!timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null;

  return { tokenId, userId };
}

// POST /api/checkin
// Body: { qrPayload: string }
// Auth: any authenticated user with STAFF or ADMIN role
export async function POST(req: NextRequest) {
  const user = await getAuthUser(req);
  if (!user) return unauthorized();

  if (user.role !== "STAFF" && user.role !== "ADMIN") {
    return NextResponse.json({ error: "Forbidden — STAFF or ADMIN role required" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { qrPayload } = body as { qrPayload?: string };

  if (!qrPayload) {
    return NextResponse.json({ error: "qrPayload is required" }, { status: 400 });
  }

  const parsed = validateQrPayload(qrPayload.trim());
  if (parsed === null) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }
  const { tokenId, userId } = parsed;

  const ticket = await prisma.ticket.findUnique({
    where:   { tokenId },
    include: { event: { select: { title: true, venue: true, city: true, eventDate: true } } },
  });

  if (!ticket) {
    return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
  }

  // Verify the QR was generated by the current ticket owner, not someone who previously held it
  const ticketOwner = await prisma.user.findFirst({
    where: { walletAddress: { equals: ticket.ownerAddress, mode: "insensitive" } },
  });
  if (!ticketOwner || ticketOwner.id !== userId) {
    return NextResponse.json({ error: "Invalid or expired QR code" }, { status: 422 });
  }

  if (ticket.status === "CHECKED_IN") {
    return NextResponse.json({ error: "Ticket already checked in", tokenId }, { status: 409 });
  }
  if (ticket.status !== "VALID") {
    return NextResponse.json({
      error: `Ticket cannot be checked in — current status: ${ticket.status}`,
      tokenId,
    }, { status: 409 });
  }

  await prisma.$transaction([
    prisma.ticket.update({
      where: { tokenId },
      data:  { status: "CHECKED_IN" },
    }),
    prisma.checkin.create({
      data: {
        tokenId,
        eventId:     ticket.eventId,
        staffUserId: user.id,
      },
    }),
  ]);

  return NextResponse.json({
    ok:           true,
    tokenId,
    ticketNumber: ticket.ticketNumber,
    seat:         ticket.seat,
    event:        ticket.event,
  });
}
