// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// O Next.js lê .env.local, o dotenv sozinho lê só .env. Sem isto, `npm run
// db:migrate`/`db:seed` rodam sem DATABASE_URL e falham com um erro de SASL do
// driver pg que não deixa claro que a causa é variável de ambiente ausente.
// Precedência igual à do Next: .env.local ganha de .env.
loadEnv({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'ts-node --compiler-options {\"module\":\"CommonJS\",\"target\":\"ES2020\"} prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
